version: '3.5'
services:
  db:
    image: mysql
    volumes:
      - ./tmp/db:/var/lib/mysql/data
    environment:
      POSTGRES_PASSWORD:
  redis:
    image: redis
    command: redis-server
    volumes:
      - 'redis:/data'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
      - DB_HOST=localhost
      - DB_USERNAME=root
      - DB_PASSWORD=

volumes:
  redis:
  postgres:
